/**
 * Outbound notifications queue — list pending SMS/WhatsApp/Email rows
 * generated by the appointment triggers, mark sent/skipped/retry.
 */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { z } from "zod";

type Role = "admin" | "super_admin" | "reception" | "doctor" | "pharmacy";

async function getRoles(sb: any, userId: string): Promise<Role[]> {
  const { data } = await sb.from("user_roles").select("role").eq("user_id", userId);
  return (data ?? []).map((r: any) => r.role as Role);
}
function ensureStaff(roles: Role[]) {
  if (!roles.some((r) => (["admin", "super_admin", "reception"] as Role[]).includes(r)))
    throw new Error("ليست لديك الصلاحية.");
}

export type OutboundNotification = {
  id: string;
  channel: "in_app" | "sms" | "whatsapp" | "email";
  send_status: "pending" | "queued" | "sent" | "failed" | "skipped";
  recipient: string | null;
  title: string;
  body: string | null;
  kind: string;
  appointment_id: string | null;
  branch_id: string | null;
  created_at: string;
  sent_at: string | null;
  last_error: string | null;
};

const ListInput = z
  .object({
    channel: z.enum(["sms", "whatsapp", "email", "in_app"]).nullable().optional(),
    status: z
      .enum(["pending", "queued", "sent", "failed", "skipped"])
      .nullable()
      .optional(),
    branchId: z.string().uuid().nullable().optional(),
    limit: z.number().int().min(1).max(500).optional(),
  })
  .default({});

export const listOutboundNotifications = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => ListInput.parse(d))
  .handler(async ({ data, context }): Promise<OutboundNotification[]> => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    let q = context.supabase
      .from("notifications")
      .select(
        "id, channel, send_status, recipient, title, body, kind, appointment_id, branch_id, created_at, sent_at, last_error",
      )
      .order("created_at", { ascending: false })
      .limit(data.limit ?? 100);
    // Default: exclude in-app (they're delivered immediately)
    q = data.channel ? q.eq("channel", data.channel) : q.neq("channel", "in_app");
    if (data.status) q = q.eq("send_status", data.status);
    if (data.branchId) q = q.eq("branch_id", data.branchId);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);
    return (rows ?? []) as unknown as OutboundNotification[];
  });

export const outboundNotificationStats = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) =>
    z.object({ branchId: z.string().uuid().nullable().optional() }).default({}).parse(d),
  )
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    const channels = ["sms", "whatsapp", "email"] as const;
    const stats: Record<string, { pending: number; sent: number; failed: number }> = {};
    for (const c of channels) {
      const base = () => {
        let b = context.supabase
          .from("notifications")
          .select("id", { count: "exact", head: true })
          .eq("channel", c);
        if (data.branchId) b = b.eq("branch_id", data.branchId);
        return b;
      };
      const [p, s, f] = await Promise.all([
        base().eq("send_status", "pending"),
        base().eq("send_status", "sent"),
        base().eq("send_status", "failed"),
      ]);
      stats[c] = {
        pending: p.count ?? 0,
        sent: s.count ?? 0,
        failed: f.count ?? 0,
      };
    }
    return stats;
  });

export const setNotificationStatus = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) =>
    z
      .object({
        id: z.string().uuid(),
        status: z.enum(["pending", "queued", "sent", "failed", "skipped"]),
        error: z.string().max(1000).nullable().optional(),
      })
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    const patch: Record<string, unknown> = { send_status: data.status };
    if (data.status === "sent") patch.sent_at = new Date().toISOString();
    if (data.status === "failed" && data.error) patch.last_error = data.error;
    if (data.status === "pending") {
      patch.last_error = null;
      patch.sent_at = null;
    }
    const { error } = await context.supabase
      .from("notifications")
      .update(patch)
      .eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });
