/**
 * Outbound notifications queue — list pending SMS/WhatsApp/Email rows
 * generated by the appointment triggers, mark sent/skipped/retry.
 */
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { z } from "zod";

type Role = "admin" | "super_admin" | "reception" | "doctor" | "pharmacy";

async function getRoles(sb: any, userId: string): Promise<Role[]> {
  const { data } = await sb.from("user_roles").select("role").eq("user_id", userId);
  return (data ?? []).map((r: any) => r.role as Role);
}
function ensureStaff(roles: Role[]) {
  if (!roles.some((r) => (["admin", "super_admin", "reception"] as Role[]).includes(r)))
    throw new Error("ليست لديك الصلاحية.");
}

export type OutboundNotification = {
  id: string;
  channel: "in_app" | "sms" | "whatsapp" | "email";
  send_status: "pending" | "queued" | "sent" | "failed" | "skipped";
  recipient: string | null;
  title: string;
  body: string | null;
  kind: string;
  appointment_id: string | null;
  branch_id: string | null;
  created_at: string;
  sent_at: string | null;
  last_error: string | null;
};

const ListInput = z
  .object({
    channel: z.enum(["sms", "whatsapp", "email", "in_app"]).nullable().optional(),
    status: z
      .enum(["pending", "queued", "sent", "failed", "skipped"])
      .nullable()
      .optional(),
    branchId: z.string().uuid().nullable().optional(),
    limit: z.number().int().min(1).max(500).optional(),
  })
  .default({});

export const listOutboundNotifications = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => ListInput.parse(d))
  .handler(async ({ data, context }): Promise<OutboundNotification[]> => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    let q = context.supabase
      .from("notifications")
      .select(
        "id, channel, send_status, recipient, title, body, kind, appointment_id, branch_id, created_at, sent_at, last_error",
      )
      .order("created_at", { ascending: false })
      .limit(data.limit ?? 100);
    // Default: exclude in-app (they're delivered immediately)
    q = data.channel ? q.eq("channel", data.channel) : q.neq("channel", "in_app");
    if (data.status) q = q.eq("send_status", data.status);
    if (data.branchId) q = q.eq("branch_id", data.branchId);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);
    return (rows ?? []) as unknown as OutboundNotification[];
  });

export const outboundNotificationStats = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) =>
    z.object({ branchId: z.string().uuid().nullable().optional() }).default({}).parse(d),
  )
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    const channels = ["sms", "whatsapp", "email"] as const;
    const stats: Record<string, { pending: number; sent: number; failed: number }> = {};
    for (const c of channels) {
      const base = () => {
        let b = context.supabase
          .from("notifications")
          .select("id", { count: "exact", head: true })
          .eq("channel", c);
        if (data.branchId) b = b.eq("branch_id", data.branchId);
        return b;
      };
      const [p, s, f] = await Promise.all([
        base().eq("send_status", "pending"),
        base().eq("send_status", "sent"),
        base().eq("send_status", "failed"),
      ]);
      stats[c] = {
        pending: p.count ?? 0,
        sent: s.count ?? 0,
        failed: f.count ?? 0,
      };
    }
    return stats;
  });

export const setNotificationStatus = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) =>
    z
      .object({
        id: z.string().uuid(),
        status: z.enum(["pending", "queued", "sent", "failed", "skipped"]),
        error: z.string().max(1000).nullable().optional(),
      })
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    const patch: Record<string, unknown> = { send_status: data.status };
    if (data.status === "sent") patch.sent_at = new Date().toISOString();
    if (data.status === "failed" && data.error) patch.last_error = data.error;
    if (data.status === "pending") {
      patch.last_error = null;
      patch.sent_at = null;
    }
    const { error } = await context.supabase
      .from("notifications")
      .update(patch as never)
      .eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/* -------- Reminder delivery log (staff view) -------- */

export type ReminderDelivery = {
  id: string;
  appointment_id: string | null;
  kind: string;
  audience: "user" | "staff";
  channel: "in_app" | "web_push" | "sms" | "whatsapp" | "email";
  send_status: "pending" | "queued" | "sent" | "failed" | "skipped";
  title: string;
  body: string | null;
  created_at: string;
  sent_at: string | null;
  last_error: string | null;
  metadata: import("@/integrations/supabase/types").Json | null;
  appointment: {
    id: string;
    patient_name: string | null;
    patient_phone: string | null;
    appointment_date: string | null;
    appointment_time: string | null;
    status: string | null;
    branch_id: string | null;
  } | null;
};

const ListRemindersInput = z
  .object({
    appointmentId: z.string().uuid().nullable().optional(),
    channel: z.enum(["in_app", "web_push", "sms", "whatsapp", "email"]).nullable().optional(),
    audience: z.enum(["user", "staff"]).nullable().optional(),
    status: z.enum(["pending", "queued", "sent", "failed", "skipped"]).nullable().optional(),
    branchId: z.string().uuid().nullable().optional(),
    limit: z.number().int().min(1).max(500).optional(),
  })
  .default({});

export const listReminderDeliveries = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => ListRemindersInput.parse(d))
  .handler(async ({ data, context }): Promise<ReminderDelivery[]> => {
    const roles = await getRoles(context.supabase, context.userId);
    ensureStaff(roles);
    let q = context.supabase
      .from("notifications")
      .select(
        "id, appointment_id, kind, audience, channel, send_status, title, body, created_at, sent_at, last_error, metadata",
      )
      .like("kind", "reminder_%")
      .order("created_at", { ascending: false })
      .limit(data.limit ?? 200);
    if (data.appointmentId) q = q.eq("appointment_id", data.appointmentId);
    if (data.channel) q = q.eq("channel", data.channel);
    if (data.audience) q = q.eq("audience", data.audience);
    if (data.status) q = q.eq("send_status", data.status);
    if (data.branchId) q = q.eq("branch_id", data.branchId);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);

    const apptIds = Array.from(
      new Set((rows ?? []).map((r) => r.appointment_id).filter((v): v is string => !!v)),
    );
    const apptMap = new Map<string, ReminderDelivery["appointment"]>();
    if (apptIds.length > 0) {
      const { data: appts, error: aErr } = await context.supabase
        .from("appointments")
        .select("id, patient_name, patient_phone, appointment_date, appointment_time, status, branch_id")
        .in("id", apptIds);
      if (aErr) throw new Error(aErr.message);
      for (const a of appts ?? []) {
        apptMap.set(a.id, {
          id: a.id,
          patient_name: a.patient_name ?? null,
          patient_phone: a.patient_phone ?? null,
          appointment_date: a.appointment_date ?? null,
          appointment_time: a.appointment_time ?? null,
          status: (a.status as string | null) ?? null,
          branch_id: a.branch_id ?? null,
        });
      }
    }
    return (rows ?? []).map((r) => ({
      ...r,
      appointment: r.appointment_id ? apptMap.get(r.appointment_id) ?? null : null,
    })) as unknown as ReminderDelivery[];
  });
  });

/* -------- Per-user notifications (bell) -------- */

const ListMyInput = z
  .object({
    limit: z.number().int().min(1).max(100).optional(),
    onlyUnread: z.boolean().optional(),
  })
  .default({});

export const listMyNotifications = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => ListMyInput.parse(d))
  .handler(async ({ data, context }) => {
    const sb = context.supabase;
    const userId = context.userId;
    const roles = await getRoles(sb, userId);
    const isStaff = roles.some((r) =>
      (["admin", "super_admin", "reception", "doctor"] as Role[]).includes(r),
    );
    let q = sb
      .from("notifications")
      .select(
        "id, audience, kind, title, body, appointment_id, metadata, read_at, created_at",
      )
      .eq("channel", "in_app")
      .order("created_at", { ascending: false })
      .limit(data.limit ?? 30);
    q = isStaff
      ? q.or(`audience.eq.staff,user_id.eq.${userId}`)
      : q.eq("user_id", userId);
    if (data.onlyUnread) q = q.is("read_at", null);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);
    return { items: rows ?? [] };
  });

export const countUnreadNotifications = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const sb = context.supabase;
    const userId = context.userId;
    const roles = await getRoles(sb, userId);
    const isStaff = roles.some((r) =>
      (["admin", "super_admin", "reception", "doctor"] as Role[]).includes(r),
    );
    let q = sb
      .from("notifications")
      .select("id", { count: "exact", head: true })
      .is("read_at", null)
      .eq("channel", "in_app");
    q = isStaff
      ? q.or(`audience.eq.staff,user_id.eq.${userId}`)
      : q.eq("user_id", userId);
    const { count, error } = await q;
    if (error) throw new Error(error.message);
    return { count: count ?? 0 };
  });

export const markNotificationsRead = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) =>
    z
      .object({
        id: z.string().uuid().optional(),
        all: z.boolean().optional(),
      })
      .refine((v) => v.id || v.all, "id or all required")
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const sb = context.supabase;
    const userId = context.userId;
    const roles = await getRoles(sb, userId);
    const isStaff = roles.some((r) =>
      (["admin", "super_admin", "reception", "doctor"] as Role[]).includes(r),
    );
    let q = sb.from("notifications").update({ read_at: new Date().toISOString() });
    if (data.id) q = q.eq("id", data.id);
    else q = q.is("read_at", null);
    q = isStaff
      ? q.or(`audience.eq.staff,user_id.eq.${userId}`)
      : q.eq("user_id", userId);
    const { error } = await q;
    if (error) throw new Error(error.message);
    return { ok: true };
  });
