/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplexRouteImport } from './routes/complex'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialtiesIndexRouteImport } from './routes/specialties.index'
import { Route as HealthIndexRouteImport } from './routes/health.index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties.$slug'
import { Route as HealthSlugRouteImport } from './routes/health.$slug'
import { Route as DoctorsSlugRouteImport } from './routes/doctors.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicBookCreateRouteImport } from './routes/api/public/book/create'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexRoute = ComplexRouteImport.update({
  id: '/complex',
  path: '/complex',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesIndexRoute = SpecialtiesIndexRouteImport.update({
  id: '/specialties/',
  path: '/specialties/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSlugRoute = HealthSlugRouteImport.update({
  id: '/health/$slug',
  path: '/health/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBookCreateRoute = ApiPublicBookCreateRouteImport.update({
  id: '/api/public/book/create',
  path: '/api/public/book/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lookup': typeof LookupRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my': typeof AuthenticatedMyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lookup': typeof LookupRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my': typeof AuthenticatedMyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors': typeof DoctorsIndexRoute
  '/health': typeof HealthIndexRoute
  '/specialties': typeof SpecialtiesIndexRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lookup': typeof LookupRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/my': typeof AuthenticatedMyRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/complex'
    | '/contact'
    | '/faq'
    | '/lookup'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/admin'
    | '/my'
    | '/settings'
    | '/doctors/$slug'
    | '/health/$slug'
    | '/specialties/$slug'
    | '/doctors/'
    | '/health/'
    | '/specialties/'
    | '/api/public/book/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/complex'
    | '/contact'
    | '/faq'
    | '/lookup'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/admin'
    | '/my'
    | '/settings'
    | '/doctors/$slug'
    | '/health/$slug'
    | '/specialties/$slug'
    | '/doctors'
    | '/health'
    | '/specialties'
    | '/api/public/book/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/complex'
    | '/contact'
    | '/faq'
    | '/lookup'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/my'
    | '/_authenticated/settings'
    | '/doctors/$slug'
    | '/health/$slug'
    | '/specialties/$slug'
    | '/doctors/'
    | '/health/'
    | '/specialties/'
    | '/api/public/book/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ComplexRoute: typeof ComplexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LookupRoute: typeof LookupRoute
  PharmacyRoute: typeof PharmacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  HealthSlugRoute: typeof HealthSlugRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  SpecialtiesIndexRoute: typeof SpecialtiesIndexRoute
  ApiPublicBookCreateRoute: typeof ApiPublicBookCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complex': {
      id: '/complex'
      path: '/complex'
      fullPath: '/complex'
      preLoaderRoute: typeof ComplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/': {
      id: '/specialties/'
      path: '/specialties'
      fullPath: '/specialties/'
      preLoaderRoute: typeof SpecialtiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$slug': {
      id: '/health/$slug'
      path: '/health/$slug'
      fullPath: '/health/$slug'
      preLoaderRoute: typeof HealthSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/book/create': {
      id: '/api/public/book/create'
      path: '/api/public/book/create'
      fullPath: '/api/public/book/create'
      preLoaderRoute: typeof ApiPublicBookCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMyRoute: typeof AuthenticatedMyRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMyRoute: AuthenticatedMyRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ComplexRoute: ComplexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LookupRoute: LookupRoute,
  PharmacyRoute: PharmacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  HealthSlugRoute: HealthSlugRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  SpecialtiesIndexRoute: SpecialtiesIndexRoute,
  ApiPublicBookCreateRoute: ApiPublicBookCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
