/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplexRouteImport } from './routes/complex'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialtiesIndexRouteImport } from './routes/specialties.index'
import { Route as HealthIndexRouteImport } from './routes/health.index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties.$slug'
import { Route as HealthSearchRouteImport } from './routes/health.search'
import { Route as HealthSlugRouteImport } from './routes/health.$slug'
import { Route as DoctorsSlugRouteImport } from './routes/doctors.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRbacRouteImport } from './routes/_authenticated/rbac'
import { Route as AuthenticatedPatientsManagementRouteImport } from './routes/_authenticated/patients-management'
import { Route as AuthenticatedPatientsAnalyticsRouteImport } from './routes/_authenticated/patients-analytics'
import { Route as AuthenticatedNotificationsQueueRouteImport } from './routes/_authenticated/notifications-queue'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedDoctorsManagementRouteImport } from './routes/_authenticated/doctors-management'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClinicSettingsRouteImport } from './routes/_authenticated/clinic-settings'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as ApiPublicBookCreateRouteImport } from './routes/api/public/book/create'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexRoute = ComplexRouteImport.update({
  id: '/complex',
  path: '/complex',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesIndexRoute = SpecialtiesIndexRouteImport.update({
  id: '/specialties/',
  path: '/specialties/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSearchRoute = HealthSearchRouteImport.update({
  id: '/health/search',
  path: '/health/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSlugRoute = HealthSlugRouteImport.update({
  id: '/health/$slug',
  path: '/health/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRbacRoute = AuthenticatedRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsManagementRoute =
  AuthenticatedPatientsManagementRouteImport.update({
    id: '/patients-management',
    path: '/patients-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsAnalyticsRoute =
  AuthenticatedPatientsAnalyticsRouteImport.update({
    id: '/patients-analytics',
    path: '/patients-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsQueueRoute =
  AuthenticatedNotificationsQueueRouteImport.update({
    id: '/notifications-queue',
    path: '/notifications-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorsManagementRoute =
  AuthenticatedDoctorsManagementRouteImport.update({
    id: '/doctors-management',
    path: '/doctors-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClinicSettingsRoute =
  AuthenticatedClinicSettingsRouteImport.update({
    id: '/clinic-settings',
    path: '/clinic-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBookCreateRoute = ApiPublicBookCreateRouteImport.update({
  id: '/api/public/book/create',
  path: '/api/public/book/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lookup': typeof LookupRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clinic-settings': typeof AuthenticatedClinicSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors-management': typeof AuthenticatedDoctorsManagementRoute
  '/my': typeof AuthenticatedMyRoute
  '/notifications-queue': typeof AuthenticatedNotificationsQueueRoute
  '/patients-analytics': typeof AuthenticatedPatientsAnalyticsRoute
  '/patients-management': typeof AuthenticatedPatientsManagementRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/health/search': typeof HealthSearchRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lookup': typeof LookupRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clinic-settings': typeof AuthenticatedClinicSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors-management': typeof AuthenticatedDoctorsManagementRoute
  '/my': typeof AuthenticatedMyRoute
  '/notifications-queue': typeof AuthenticatedNotificationsQueueRoute
  '/patients-analytics': typeof AuthenticatedPatientsAnalyticsRoute
  '/patients-management': typeof AuthenticatedPatientsManagementRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/health/search': typeof HealthSearchRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors': typeof DoctorsIndexRoute
  '/health': typeof HealthIndexRoute
  '/specialties': typeof SpecialtiesIndexRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/lookup': typeof LookupRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/clinic-settings': typeof AuthenticatedClinicSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctors-management': typeof AuthenticatedDoctorsManagementRoute
  '/_authenticated/my': typeof AuthenticatedMyRoute
  '/_authenticated/notifications-queue': typeof AuthenticatedNotificationsQueueRoute
  '/_authenticated/patients-analytics': typeof AuthenticatedPatientsAnalyticsRoute
  '/_authenticated/patients-management': typeof AuthenticatedPatientsManagementRoute
  '/_authenticated/rbac': typeof AuthenticatedRbacRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/health/search': typeof HealthSearchRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/complex'
    | '/contact'
    | '/faq'
    | '/lookup'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/admin'
    | '/audit-log'
    | '/calendar'
    | '/clinic-settings'
    | '/dashboard'
    | '/doctors-management'
    | '/my'
    | '/notifications-queue'
    | '/patients-analytics'
    | '/patients-management'
    | '/rbac'
    | '/reports'
    | '/settings'
    | '/doctors/$slug'
    | '/health/$slug'
    | '/health/search'
    | '/specialties/$slug'
    | '/doctors/'
    | '/health/'
    | '/specialties/'
    | '/patients/$patientId'
    | '/patients/'
    | '/api/public/book/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/complex'
    | '/contact'
    | '/faq'
    | '/lookup'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/admin'
    | '/audit-log'
    | '/calendar'
    | '/clinic-settings'
    | '/dashboard'
    | '/doctors-management'
    | '/my'
    | '/notifications-queue'
    | '/patients-analytics'
    | '/patients-management'
    | '/rbac'
    | '/reports'
    | '/settings'
    | '/doctors/$slug'
    | '/health/$slug'
    | '/health/search'
    | '/specialties/$slug'
    | '/doctors'
    | '/health'
    | '/specialties'
    | '/patients/$patientId'
    | '/patients'
    | '/api/public/book/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/complex'
    | '/contact'
    | '/faq'
    | '/lookup'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/audit-log'
    | '/_authenticated/calendar'
    | '/_authenticated/clinic-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctors-management'
    | '/_authenticated/my'
    | '/_authenticated/notifications-queue'
    | '/_authenticated/patients-analytics'
    | '/_authenticated/patients-management'
    | '/_authenticated/rbac'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/doctors/$slug'
    | '/health/$slug'
    | '/health/search'
    | '/specialties/$slug'
    | '/doctors/'
    | '/health/'
    | '/specialties/'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/'
    | '/api/public/book/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ComplexRoute: typeof ComplexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LookupRoute: typeof LookupRoute
  PharmacyRoute: typeof PharmacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  HealthSlugRoute: typeof HealthSlugRoute
  HealthSearchRoute: typeof HealthSearchRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  SpecialtiesIndexRoute: typeof SpecialtiesIndexRoute
  ApiPublicBookCreateRoute: typeof ApiPublicBookCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complex': {
      id: '/complex'
      path: '/complex'
      fullPath: '/complex'
      preLoaderRoute: typeof ComplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/': {
      id: '/specialties/'
      path: '/specialties'
      fullPath: '/specialties/'
      preLoaderRoute: typeof SpecialtiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/search': {
      id: '/health/search'
      path: '/health/search'
      fullPath: '/health/search'
      preLoaderRoute: typeof HealthSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$slug': {
      id: '/health/$slug'
      path: '/health/$slug'
      fullPath: '/health/$slug'
      preLoaderRoute: typeof HealthSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rbac': {
      id: '/_authenticated/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof AuthenticatedRbacRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients-management': {
      id: '/_authenticated/patients-management'
      path: '/patients-management'
      fullPath: '/patients-management'
      preLoaderRoute: typeof AuthenticatedPatientsManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients-analytics': {
      id: '/_authenticated/patients-analytics'
      path: '/patients-analytics'
      fullPath: '/patients-analytics'
      preLoaderRoute: typeof AuthenticatedPatientsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications-queue': {
      id: '/_authenticated/notifications-queue'
      path: '/notifications-queue'
      fullPath: '/notifications-queue'
      preLoaderRoute: typeof AuthenticatedNotificationsQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors-management': {
      id: '/_authenticated/doctors-management'
      path: '/doctors-management'
      fullPath: '/doctors-management'
      preLoaderRoute: typeof AuthenticatedDoctorsManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinic-settings': {
      id: '/_authenticated/clinic-settings'
      path: '/clinic-settings'
      fullPath: '/clinic-settings'
      preLoaderRoute: typeof AuthenticatedClinicSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/book/create': {
      id: '/api/public/book/create'
      path: '/api/public/book/create'
      fullPath: '/api/public/book/create'
      preLoaderRoute: typeof ApiPublicBookCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClinicSettingsRoute: typeof AuthenticatedClinicSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorsManagementRoute: typeof AuthenticatedDoctorsManagementRoute
  AuthenticatedMyRoute: typeof AuthenticatedMyRoute
  AuthenticatedNotificationsQueueRoute: typeof AuthenticatedNotificationsQueueRoute
  AuthenticatedPatientsAnalyticsRoute: typeof AuthenticatedPatientsAnalyticsRoute
  AuthenticatedPatientsManagementRoute: typeof AuthenticatedPatientsManagementRoute
  AuthenticatedRbacRoute: typeof AuthenticatedRbacRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClinicSettingsRoute: AuthenticatedClinicSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorsManagementRoute: AuthenticatedDoctorsManagementRoute,
  AuthenticatedMyRoute: AuthenticatedMyRoute,
  AuthenticatedNotificationsQueueRoute: AuthenticatedNotificationsQueueRoute,
  AuthenticatedPatientsAnalyticsRoute: AuthenticatedPatientsAnalyticsRoute,
  AuthenticatedPatientsManagementRoute: AuthenticatedPatientsManagementRoute,
  AuthenticatedRbacRoute: AuthenticatedRbacRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ComplexRoute: ComplexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LookupRoute: LookupRoute,
  PharmacyRoute: PharmacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  HealthSlugRoute: HealthSlugRoute,
  HealthSearchRoute: HealthSearchRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  SpecialtiesIndexRoute: SpecialtiesIndexRoute,
  ApiPublicBookCreateRoute: ApiPublicBookCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
